import { DataType } from "./ProductCategory";

const datas: DataType[] = [
  {
    value: 1,
    title: "Electronics",
    featured: true,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 11,
        title: "Smartphones",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 12,
        title: "Laptops",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 13,
        title: "Tablets",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 2,
    title: "Home Appliances",
    featured: false,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 21,
        title: "Refrigerators",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 22,
        title: "Washing Machines",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 23,
        title: "Microwaves",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 3,
    title: "Furniture",
    featured: true,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 31,
        title: "Sofas",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 32,
        title: "Beds",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 33,
        title: "Dining Tables",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 4,
    title: "Clothing",
    featured: false,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 41,
        title: "Men's Wear",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 42,
        title: "Women's Wear",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 43,
        title: "Kids' Wear",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 5,
    title: "Books",
    featured: true,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 51,
        title: "Fiction",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 52,
        title: "Non-Fiction",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 53,
        title: "Comics",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 6,
    title: "Toys",
    featured: false,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 61,
        title: "Action Figures",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 62,
        title: "Board Games",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 63,
        title: "Puzzles",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 7,
    title: "Sports Equipment",
    featured: true,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 71,
        title: "Football",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 72,
        title: "Basketball",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 73,
        title: "Tennis",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 8,
    title: "Beauty Products",
    featured: false,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 81,
        title: "Makeup",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 82,
        title: "Skincare",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 83,
        title: "Haircare",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 9,
    title: "Groceries",
    featured: true,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 91,
        title: "Fruits",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 92,
        title: "Vegetables",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 93,
        title: "Dairy",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
  {
    value: 10,
    title: "Stationery",
    featured: false,
    products: "3 products",
    status: "Available",
    active: true,
    children: [
      {
        value: 101,
        title: "Pens",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
      {
        value: 102,
        title: "Notebooks",
        featured: false,
        products: "2 products",
        status: "Out of Stock",
        active: false,
      },
      {
        value: 103,
        title: "Markers",
        featured: true,
        products: "2 products",
        status: "Available",
        active: true,
      },
    ],
  },
];

export default datas;
