import { DataType } from "./ProductCategory";

const datas: DataType[] = [
    {
        key: 1,
        name: "Electronics",
        featured: true,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 11,
            name: "Smartphones",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 12,
            name: "Laptops",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 13,
            name: "Tablets",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 2,
        name: "Home Appliances",
        featured: false,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 21,
            name: "Refrigerators",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 22,
            name: "Washing Machines",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 23,
            name: "Microwaves",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 3,
        name: "Furniture",
        featured: true,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 31,
            name: "Sofas",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 32,
            name: "Beds",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 33,
            name: "Dining Tables",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 4,
        name: "Clothing",
        featured: false,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 41,
            name: "Men's Wear",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 42,
            name: "Women's Wear",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 43,
            name: "Kids' Wear",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 5,
        name: "Books",
        featured: true,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 51,
            name: "Fiction",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 52,
            name: "Non-Fiction",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 53,
            name: "Comics",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 6,
        name: "Toys",
        featured: false,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 61,
            name: "Action Figures",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 62,
            name: "Board Games",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 63,
            name: "Puzzles",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 7,
        name: "Sports Equipment",
        featured: true,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 71,
            name: "Football",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 72,
            name: "Basketball",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 73,
            name: "Tennis",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 8,
        name: "Beauty Products",
        featured: false,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 81,
            name: "Makeup",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 82,
            name: "Skincare",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 83,
            name: "Haircare",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 9,
        name: "Groceries",
        featured: true,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 91,
            name: "Fruits",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 92,
            name: "Vegetables",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 93,
            name: "Dairy",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
      {
        key: 10,
        name: "Stationery",
        featured: false,
        products: "3 products",
        status: "Available",
        active: true,
        children: [
          {
            key: 101,
            name: "Pens",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
          {
            key: 102,
            name: "Notebooks",
            featured: false,
            products: "2 products",
            status: "Out of Stock",
            active: false,
          },
          {
            key: 103,
            name: "Markers",
            featured: true,
            products: "2 products",
            status: "Available",
            active: true,
          },
        ],
      },
    ];
  
  export default datas;